### ISSUE TITLE
LUI instruction throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by leopoldwe** [EduMIPS64/edumips64#475] opened 2020-10-19 21:55 UTC
I was writing a unit test for LUI, but it throws an IndexOutOfBoundsException.

The instruction I am trying to run:
`lui r2 63`

When I looked into it, it looks like the exception is thrown when `checkImmediateForOverflow()` is called, which expects the immediate to be at index 2, but there are only 2 arguments.

**Comment by lupino3** [comment] 2020-10-20 09:29
Hi @leopoldwe, thanks a lot for the bug report!

I'll try to get to it this week, I have a couple of bugs to address and need to make a new release.

**Comment by lupino3** [comment] 2020-10-20 09:30
BTW thanks for the precise instructions on how to reproduce it, this will make it much easier to debug and (hopefully) fix! :)

**Comment by lupino3** [comment] 2020-10-21 13:19
Hi @leopoldwe, your code is missing a comma between `r2` and `63`. It should be `lui r2, 63`.

The GUI correctly handles this case, displaying an appropriate error message:
![image](https://user-images.githubusercontent.com/200139/96724998-55cf1400-13a8-11eb-9a49-4f6efdbace70.png)

I am going to close this bug, since the simulator is working as intended. Thanks for the bug report!

**Comment by leopoldwe** [comment] 2020-10-21 14:35
![Screen Shot 2020-10-21 at 10 32 48 AM](https://user-images.githubusercontent.com/8764781/96734722-d251fa80-1388-11eb-9be5-634c62e7029d.png)

Nope, still doesn't work. I wrote my code wrong in my comment, is all.

**Comment by lupino3** [comment] 2020-10-21 15:25
Thanks, I'll look into it ASAP! Could you copy/paste the whole text in the error dialog into a comment on the issue? It contains some diagnostic information. Thanks!

**Comment by leopoldwe** [comment] 2020-10-21 17:40
```java
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
	at java.base/java.util.LinkedList.get(LinkedList.java:480)
	at org.edumips64.core.is.ALU_IType.checkImmediateForOverflow(ALU_IType.java:64)
	at org.edumips64.core.is.LUI.ID(LUI.java:59)
	at org.edumips64.core.CPU.stepID(CPU.java:636)
	at org.edumips64.core.CPU.step(CPU.java:414)
	at org.edumips64.ui.swing.CPUSwingWorker.doInBackground(CPUSwingWorker.java:180)
	at org.edumips64.ui.swing.CPUSwingWorker.doInBackground(CPUSwingWorker.java:1)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
## System information
 * Version: null
 * Build date: null
 * Git revision: null
 * JRE version: 11.0.8
 * OS: Mac OS X

## Code of the assembly file in execution
<details><summary>Click to expand</summary>

```assembly
.data .word32 4128768
.code
lw r1,0(r0)
lui r2,63
bne r1,r2,error
syscall 0
error:
break
syscall 0

```
</details>

**Comment by lupino3** [comment] 2020-10-22 09:50
Thank you! I was able to reproduce the issue and will try to work on it as soon as possible.

**Comment by lupino3** [comment] 2020-10-22 10:38
Found the bug. The code relies on the wrong assumption that overriding attributes works in Java. `LUI.java` re-defines `IMM_FIELD = 1`, and expects `checkImmediateForOverflow` to use this value, but `checkImmediateForOverflow` is defined in `ALU_IType`, where the value of that variable is `2`, hence the overflow.

Since this type of override doesn't work in Java, I'll have to re-think how to set those instruction-level values so that base classes can access them.

**Closed** 2020-10-22 11:25 UTC
Labels: component:parser, priority:0, type:bug

**Comment by lupino3** [comment] 2020-10-22 15:02
Fixed the bug, thanks @leopoldwe!

By the way, whenever you have time could you send a PR with the unit tests you are developing? They will come useful as a regression test for this issue as well.

Thanks!
