### ISSUE TITLE
Infinite RAW stall in floating-point code

### ISSUE THREAD

**Issue by jcarletta** [EduMIPS64/edumips64#304] opened 2020-04-05 19:42 UTC
The attached code exposes an apparent bug in EduMIPS; I tested in v1.2.6 (standalone) and v1.2.5.  For this code, floating-point instructions reach the MEM stage at the same time that an integer instruction does.  The integer instruction's MEM and WB stages are apparently never accounted for, and a consequent integer instruction infinitely RAW stalls.

My students found this bug in working on a project.  (EduMIPS has been a great learning tool overall for my class.)  I've pared out some code that wasn't need to expose the bug, and
added comments about what I see in the cycle window and register values that is not accurate.

[Infinite RAW stall code.txt](https://github.com/EduMIPS64/edumips64/files/4434644/Infinite.RAW.stall.code.txt)

**Comment by lupino3** [comment] 2020-04-05 20:24
Hi and thanks for the bug report and for the easy-to-reproduce case.

I tried running the attached code and verified that indeed this seems to be a bug (actually, it seems like there are several bugs here). It'll take me some time to fix them :) I hope to have some time next week-end.

Thanks a lot and to your students for contributing to raising the quality of our simulator!

**Comment by lupino3** [comment] 2020-04-05 20:27
I have one question to you: could you please allow me to use your code as a unit test for EduMIPS64, releasing it as GPL code? That will allow me to use it as a regression test once I fix the bug(s). Thanks!

**Comment by jcarletta** [comment] 2020-04-05 21:16
Thanks for your reply – that was fast!  Yes, you may use the code as needed.  --Joan


Dr. Joan Carletta
Associate Dean for Undergraduate Studies
College of Engineering
The University of Akron
Akron, OH 44325-3901
Office: 330-972-7691
www.uakron.edu/engineering/<http://www.uakron.edu/engineering/>

[Wordmark for The University of Akron]

**Comment by lupino3** [comment] 2020-04-05 22:58
Thank you very much! I found and fixed the bug where MEM/WB for one instruction were not executed (https://github.com/EduMIPS64/edumips64/commit/4e65f115736d1e629ec2d1ee29f674eb0d97c52a), just need to add a regression test for it.

Unfortunately the bug where MEM/WB are not visible in the Cycle UI is harder to fix and will require a couple of hours of work, I hope to be able to do it next weekend and push out a new release.

I hope you can live with the temporary workaround that you found for the time being. Thanks again for the bug reports!

**Comment by jcarletta** [comment] 2020-04-06 00:32
I truly appreciate the work you’ve done!  This will help my students a lot, and we can definitely workaround the MEM and WB stages not being visible in the Cycles window.  –Joan

**Comment by lupino3** [comment] 2020-04-11 08:34
Note for self on things to do:

- [ ] unit test for the infinite RAW stall bug (i.e., EX being overridden on RAW stalls generated by FPU)
- [ ] unit tests for wrong terminating CycleElement state for some FP instructions
- [ ] fix bug with wrong terminating CycleElement state (caused by short look-back in the state progression algorithm in CycleBuilder -- should be fixed by keeping in memory the exact working set of instructions)
- [ ] see if it's possible to do CycleBuilder checks on wrong terminating element at run-time, and emit a SEVERE log statement
- [ ] see if it's possible to have SEVERE log statements fail unit tests.

**Comment by lupino3** [comment] 2020-04-11 08:35
Sorry for the delay, busy week. I hope to have some time this weekend or next week!

**Comment by lupino3** [comment] 2020-04-11 18:10
@jcarletta the standalone JAR from the latest commit to `master` contains the fix for the infinite RAW stall: https://github.com/EduMIPS64/edumips64/actions/runs/76054445

Once I manage to fix the second bug as well I'll release a new version (1.2.7) with both fixes.

**Comment by lupino3** [comment] 2020-04-11 21:47
@jcarletta just released v1.2.7, which should contain a fix for both issues: https://github.com/EduMIPS64/edumips64/releases/tag/v1.2.7. Thanks a lot for the detailed bug report!

**Comment by hugmanrique** [comment] 2021-11-12 23:34
It seems that this bug is appearing in some other place. The following program causes EduMIPS to stall endlessly due to a RAW dependency on F8:
```assembly
 .data
v: .space 256
w: .space 256
x: .double 2.0
y: .double 1.5
z: .double 0.0
.text
daddi R1, R0, v
daddi R2, R0, w
daddi R3, R0, 256

ldc1 F2, x(R0)
ldc1 F4, y(R0)
daddi R4, R0, 0

loop1:
dmtc1 R4, F6
daddi R4, R4, 8
cvt.d.l F6, F6
mul.d F8, F2, F6
mul.d F10, F4, F6
dmtc1 R4, F12
daddi R4, R4, 8
cvt.d.l F12, F12
mul.d F14, F2, F12
daddi R1, R1, 16
mul.d F8, F8, F8
daddi R2, R2, 16

sdc1 F10, -16(R2)
mul.d F14, F14, F14
mul.d F16, F4, F12
sdc1 F8, -16(R1) ; here 
sdc1 F14, -8(R1) ;
sdc1 F16, -8(R2)
bne R4, R3, loop1
syscall 0
```

I've tried running the program with release 1.2.9 and the latest release on the CI (1.2.9-alpha-bbb71d8). The code is part of a class assignment, so I cannot release it under an open source license for regression tests atm.

**Comment by lupino3** [comment] 2021-11-17 12:26
Thanks for the report @hugmanrique, I'll have a look at this as soon as possible!

**Comment by lupino3** [comment] 2021-11-19 21:17
I tried running your code and indeed I can see the stall when I enable forwarding.

**Comment by lupino3** [comment] 2021-11-19 21:37
The `RAW` exception is caused by the lack of write-back execution for the `DADDI` instruction. That leaves the instruction "locked" (the internal write semaphore is cleaned in WB) and causes `SDC1` to throw the RAW exception. Now to understand why the WB stage doesn't execute for DADDI...

**Comment by lupino3** [comment] 2021-11-19 21:41
<img width="629" alt="image" src="https://user-images.githubusercontent.com/200139/142694973-a4c577a3-091e-4b65-a04a-b74d5d4d420e.png">
`mul.d` at address `0024` enters `MEM` instead of `DADDI` and overrides it at cycle 19.

**Comment by lupino3** [comment] 2021-11-21 16:07
This is what should happen: a structural stall.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/200139/142769638-633ef1d3-4971-43d4-9bc3-c01136fbb297.png">

**Comment by lupino3** [comment] 2022-02-22 13:39
I am going to reopen this issue to keep track of the problem.

**Comment by jcarletta** [comment] 2022-02-22 15:33
I appreciate this!  My class is using EduMIPs again this year; it's very helpful to them.

**Comment by lupino3** [comment] 2022-03-02 21:23
I found the issue and should have fixed it. @hugmanrique, would you be ok now with me using your sample code as a unit test?

**Comment by hugmanrique** [comment] 2022-03-04 18:39
Sure, go ahead. I release the code to the public domain.

Thank you for the fix!

**Comment by lupino3** [comment] 2022-03-05 07:52
Added, thanks @hugmanrique !

**Closed** 2022-03-05 08:07 UTC
Labels: type:bug, component:core, priority:0
